import { generateRandomID } from "@/utils";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form
        className={`${"flex flex-col grow-0 items-center content-center"}`}
        onSubmit={(e) => {
          e.preventDefault();
          router.push({
            pathname: "/game",
            query: {
              room: generateRandomID(),
              player: 0,
            },
          });
        }}
      >
        <button>Create room</button>
        OR
      </form>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          const target = e.target as typeof e.target & {
            room: { value: string };
          };
          router.push({
            pathname: "/game",
            query: {
              room: target.room.value,
              player: 1,
            },
          });
        }}
      >
        <div className="flex gap-2">
          <button>Join</button>
          <label htmlFor="room">room id</label>
          <input id="room" placeholder="room id"></input>
        </div>
      </form>
    </>
  );
}
